class neutron::config{
    Exec{
        path=>"/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/bin:/sbin",
        logoutput=>"on_failure",
    }
    define file($ip,$controller,$passwd){
        file{"/etc/neutron/neutron.conf":
            ensure=>present,
            content=>template("neutron/neutron.conf.erb"),
            require=>Class["neutron::install"],
            notify=>file["/etc/neutron/plugins/ml2/ml2_conf.ini"],
        }
        file{"/etc/neutron/plugins/ml2/ml2_conf.ini":
            ensure=>present,
            content=>template("neutron/ml2_conf.ini.erb"),
            require=>File["/etc/neutron/neutron.conf"],
            notify=>File["/etc/neutron/plugins/ml2/linuxbridge_agent.ini"],
        }
        file{"/etc/neutron/plugins/ml2/linuxbridge_agent.ini":
            ensure=>present,
            content=>template("neutron/linuxbridge_agent.ini.erb"),
            require=>File["/etc/neutron/plugins/ml2/ml2_conf.ini"],
            notify=>File["/etc/neutron/l3_agent.ini"],
        }
        file{"/etc/neutron/l3_agent.ini":
            ensure=>present,
            content=>template("neutron/l3_agent.ini.erb"),
            require=>File["/etc/neutron/plugins/ml2/linuxbridge_agent.ini"],
            notify=>File["/etc/neutron/dhcp_agent.ini"],
        }
        file{"/etc/neutron/dhcp_agent.ini":
            ensure=>present,
            content=>template("neutron/dhcp_agent.ini.erb"),
            require=>File["/etc/neutron/l3_agent.ini"],
            notify=>File["/etc/neutron/metadata_agent.ini"],
        }
        file{"/etc/neutron/metadata_agent.ini":
            ensure=>present,
            content=>template("neutron/metadata_agent.ini.erb"),
            require=>File["/etc/neutron/dhcp_agent.ini"],
            notify=>Class["neutron::service"],
        }
    }
}
